# Don't print a new line at the start of the prompt
add_newline = false

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

[battery]
[[battery.display]]  # バッテリー残量が0％〜30％の間は「太字の赤色」スタイルを利用する
threshold = 30
style = "bold red"

[[battery.display]]  # バッテリー残量が30％〜50％の間は「太字の黄色」スタイルを利用する
threshold = 50
style = "bold yellow"

[character]
symbol = "➜"
error_symbol = "✗"
use_symbol_for_status = true
style_success = "#ff69b4"

[cmd_duration]

[directory]
style = "#ba55d3"
truncation_length = 0
truncate_to_repo = false

[elm]

[env_var]

[git_branch]
style = "#dda0dd"
truncation_length = 10

[git_commit]
disabled = false
commit_hash_length = 7

[git_state]
progress_divider = " of "

[git_status]
staged.value = "++"
staged.style = "green"
staged_count.enabled = true
staged_count.style = "green"

[hostname]
ssh_only = false
prefix = "⟪"
suffix = "⟫"
trim_at = ".companyname.com"
disabled = true

[jobs]
symbol = "+ "
threshold = 4

[line_break]

[memory_usage]
show_percentage = true
show_swap = true
threshold = -1
symbol = " "
separator = "/"
style = "bold dimmed green"

[nodejs]
disabled = false

[ruby]

[rust]

[package]
disabled = true
